In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [6]:
iris = load_iris()
x = iris.data
y = iris.target
features = iris.feature_names

In [7]:
df = pd.DataFrame(x, columns=features)
df["species"] = y

In [8]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  species
0                  5.1               3.5                1.4               0.2        0
1                  4.9               3.0                1.4               0.2        0
2                  4.7               3.2                1.3               0.2        0
3                  4.6               3.1                1.5               0.2        0
4                  5.0               3.6                1.4               0.2        0
..                 ...               ...                ...               ...      ...
145                6.7               3.0                5.2               2.3        2
146                6.3               2.5                5.0               1.9        2
147                6.5               3.0                5.2               2.0        2
148                6.2               3.4                5.4               2.3        2
149                5.9               3.0                5.1               1.8        2

[150 rows x 5 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [11]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [12]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  species
0                  5.1               3.5                1.4               0.2        0
1                  4.9               3.0                1.4               0.2        0
2                  4.7               3.2                1.3               0.2        0
3                  4.6               3.1                1.5               0.2        0
4                  5.0               3.6                1.4               0.2        0
..                 ...               ...                ...               ...      ...
145                6.7               3.0                5.2               2.3        2
146                6.3               2.5                5.0               1.9        2
147                6.5               3.0                5.2               2.0        2
148                6.2               3.4                5.4               2.3        2
149                5.9               3.0                5.1               1.8        2

[150 rows x 5 columns]

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled,y, test_size=0.3, random_state=60)

In [16]:
models = { "Logistic Regresyon": LogisticRegression(),
           "KN": KNeighborsClassifier(),
           "SVM": SVC()}

In [17]:
accuracy_values = {}

In [19]:
for model_name, model in models.items():
    model.fit(x_train, y_train)
    y_prediction = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_prediction)

    accuracy_values[model_name] = accuracy

In [21]:
print("DoÄŸruluk oranlarÄ±")
for model_name, accuracy in accuracy_values.items():
    print(f"{model_name}: {accuracy * 100: .3f}")

DoÄŸruluk oranlarÄ±
Logistic Regresyon:  91.111
KN:  95.556
SVM:  91.111